apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  application-dev.yml: |
    server:
      port: 8080
    spring:
      cloud:
        gateway:
          mvc:
            routes:
              - id: backend-user
                uri: http://user-service:8080
                predicates:
                  - Path=/api/user/**
                filters:
                  - AddAuthenticationHeader
              - id: backend-alim
                uri: http://alim-service:8080
                predicates:
                  - Path=/api/alim/**
                filters:
                  - AddAuthenticationHeader
              - id: backend-news
                uri: http://news-service:8080
                predicates:
                  - Path=/api/news/**
                filters:
                  - AddAuthenticationHeader